// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QUANLYTHUVIEN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230528163942_Create_table_Author")]
    partial class Create_table_Author
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("QUANLYTHUVIEN.Models.Author", b =>
                {
                    b.Property<string>("AuthorID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorID");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("QUANLYTHUVIEN.Models.Nhaxuatban", b =>
                {
                    b.Property<string>("NXBID")
                        .HasColumnType("TEXT");

                    b.Property<string>("NXBAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NXBName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phone")
                        .HasColumnType("INTEGER");

                    b.HasKey("NXBID");

                    b.ToTable("Nhaxuatban");
                });
#pragma warning restore 612, 618
        }
    }
}
